// ARRAY CENTRAL DE VAGAS
let vagas = JSON.parse(localStorage.getItem("vagas")) || [
    {
        id: 1,
        titulo: "Desenvolvedor Front-end",
        empresa: "Empresa XYZ",
        empresaId: 1,
        local: "Presidente Prudente, SP",
        modalidade: "home",
        contrato: "clt",
        deficiencia: "fisica auditiva",
        salario_minimo: 4000,
        salario_maximo: 5500,
        descricao: "Desenvolvimento de interfaces web responsivas e acessíveis utilizando React e TypeScript.",
        data: "2026-03-10",
        status: "ativa"
    },
    {
        id: 2,
        titulo: "Analista de Dados",
        empresa: "Empresa ABC",
        empresaId: 2,
        local: "São Paulo, SP",
        modalidade: "hibrido",
        contrato: "pj",
        deficiencia: "auditiva",
        salario_minimo: 5500,
        salario_maximo: 7500,
        descricao: "Análise e interpretação de dados utilizando Python e ferramentas de BI.",
        data: "2025-12-27",
        status: "ativa"
    },
    {
        id: 3,
        titulo: "Analista de Suporte Técnico",
        empresa: "Empresa Tech",
        empresaId: 3,
        local: "Rio de Janeiro, RJ",
        modalidade: "presencial",
        contrato: "estagio",
        deficiencia: "visual",
        salario_minimo: 1500,
        salario_maximo: 2500,
        descricao: "Responsável por fornecer suporte técnico de primeiro e segundo nível aos usuários internos.",
        data: "2026-02-05",
        status: "pausada"
    },
    {
        id: 4,
        titulo: "Engenheiro de Software",
        empresa: "InovaTech",
        empresaId: 4,
        local: "Campinas, SP",
        modalidade: "hibrido",
        contrato: "clt",
        deficiencia: "todas",
        salario_minimo: 8000,
        salario_maximo: 11000,
        descricao: "Desenvolvimento de sistemas escaláveis utilizando Java e arquitetura de microsserviços.",
        data: "2026-03-28",
        status: "ativa"
    },
    {
        id: 5,
        titulo: "UX/UI Designer",
        empresa: "Creative Labs",
        empresaId: 5,
        local: "Curitiba, PR",
        modalidade: "home",
        contrato: "pj",
        deficiencia: "fisica",
        salario_minimo: 4000,
        salario_maximo: 6000,
        descricao: "Criação de interfaces e experiências digitais focadas no usuário.",
        data: "2026-01-15",
        status: "ativa"
    },
    {
        id: 6,
        titulo: "Administrador de Redes",
        empresa: "NetSolutions",
        empresaId: 6,
        local: "Belo Horizonte, MG",
        modalidade: "presencial",
        contrato: "clt",
        deficiencia: "auditiva visual",
        salario_minimo: 5000,
        salario_maximo: 7000,
        descricao: "Gerenciamento de redes corporativas, servidores e segurança da informação.",
        data: "2026-02-20",
        status: "pausada"
    },
    {
        id: 7,
        titulo: "Desenvolvedor Back-end",
        empresa: "CodeBase",
        empresaId: 7,
        local: "Florianópolis, SC",
        modalidade: "home",
        contrato: "pj",
        deficiencia: "intelectual",
        salario_minimo: 6000,
        salario_maximo: 9000,
        descricao: "Desenvolvimento de APIs RESTful utilizando Node.js e bancos de dados SQL/NoSQL.",
        data: "2026-03-05",
        status: "ativa"
    },
    {
        id: 8,
        titulo: "QA Tester",
        empresa: "QualitySoft",
        empresaId: 8,
        local: "Porto Alegre, RS",
        modalidade: "hibrido",
        contrato: "clt",
        deficiencia: "fisica",
        salario_minimo: 3000,
        salario_maximo: 4500,
        descricao: "Execução de testes manuais e automatizados para garantir a qualidade do software.",
        data: "2026-02-10",
        status: "ativa"
    },
    {
        id: 9,
        titulo: "Cientista de Dados",
        empresa: "DataMind",
        empresaId: 9,
        local: "São Paulo, SP",
        modalidade: "home",
        contrato: "pj",
        deficiencia: "todas",
        salario_minimo: 9000,
        salario_maximo: 13000,
        descricao: "Construção de modelos preditivos e análise avançada de dados.",
        data: "2026-03-30",
        status: "ativa"
    },
    {
        id: 10,
        titulo: "Estagiário em TI",
        empresa: "StartTech",
        empresaId: 10,
        local: "Presidente Prudente, SP",
        modalidade: "presencial",
        contrato: "estagio",
        deficiencia: "visual auditiva",
        salario_minimo: 1200,
        salario_maximo: 1800,
        descricao: "Apoio em atividades de suporte técnico e desenvolvimento interno.",
        data: "2026-03-18",
        status: "pausada"
    }
];